### ISSUE TITLE
Getting "Cannot find module 'parcel-bundler/src/Logger'" in Parcel 1.11.0

### ISSUE THREAD

**Issue by cheeaun** [shunia/parcel-plugin-json-url-loader#1]
Getting this warning in latest Parcel 1.11.0:

```
Server running at http://localhost:1234
⚠️  Cannot find module 'parcel-bundler/src/Logger'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (/Users/cheeaun/project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/cheeaun/project/node_modules/parcel-plugin-json-url-loader/lib/index.js:1:78)
    at Module._compile (/Users/cheeaun/project/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
✨  Built in 721ms.
```

This may be due to this change: https://github.com/parcel-bundler/parcel/pull/2165

New logger seems to be at [@parcel/logger](https://www.npmjs.com/package/@parcel/logger).

**Comment by shunia** [comment]
Well, I simply removed the unused import and published a new version to npm.
So you just need to update your plugin version to `0.1.2` and it should be resolved.

**Comment by cheeaun** [comment]
Haha nice! Thanks!
